# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: demo.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'demo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x04\x64\x65mo\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"*\n\x0cRangeRequest\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\"\x1c\n\x0bNumberReply\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1e\n\rNumberRequest\x12\r\n\x05value\x18\x01 \x01(\x05\"\x19\n\x08SumReply\x12\r\n\x05total\x18\x01 \x01(\x05\")\n\x0b\x43hatMessage\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t2\xde\x01\n\x0b\x44\x65moService\x12\x30\n\x08SayHello\x12\x12.demo.HelloRequest\x1a\x10.demo.HelloReply\x12\x36\n\x0bListNumbers\x12\x12.demo.RangeRequest\x1a\x11.demo.NumberReply0\x01\x12\x33\n\nSumNumbers\x12\x13.demo.NumberRequest\x1a\x0e.demo.SumReply(\x01\x12\x30\n\x04\x43hat\x12\x11.demo.ChatMessage\x1a\x11.demo.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=20
  _globals['_HELLOREQUEST']._serialized_end=48
  _globals['_HELLOREPLY']._serialized_start=50
  _globals['_HELLOREPLY']._serialized_end=79
  _globals['_RANGEREQUEST']._serialized_start=81
  _globals['_RANGEREQUEST']._serialized_end=123
  _globals['_NUMBERREPLY']._serialized_start=125
  _globals['_NUMBERREPLY']._serialized_end=153
  _globals['_NUMBERREQUEST']._serialized_start=155
  _globals['_NUMBERREQUEST']._serialized_end=185
  _globals['_SUMREPLY']._serialized_start=187
  _globals['_SUMREPLY']._serialized_end=212
  _globals['_CHATMESSAGE']._serialized_start=214
  _globals['_CHATMESSAGE']._serialized_end=255
  _globals['_DEMOSERVICE']._serialized_start=258
  _globals['_DEMOSERVICE']._serialized_end=480
# @@protoc_insertion_point(module_scope)
