# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import demo_pb2 as demo__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in demo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DemoServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/demo.DemoService/SayHello',
                request_serializer=demo__pb2.HelloRequest.SerializeToString,
                response_deserializer=demo__pb2.HelloReply.FromString,
                _registered_method=True)
        self.ListNumbers = channel.unary_stream(
                '/demo.DemoService/ListNumbers',
                request_serializer=demo__pb2.RangeRequest.SerializeToString,
                response_deserializer=demo__pb2.NumberReply.FromString,
                _registered_method=True)
        self.SumNumbers = channel.stream_unary(
                '/demo.DemoService/SumNumbers',
                request_serializer=demo__pb2.NumberRequest.SerializeToString,
                response_deserializer=demo__pb2.SumReply.FromString,
                _registered_method=True)
        self.Chat = channel.stream_stream(
                '/demo.DemoService/Chat',
                request_serializer=demo__pb2.ChatMessage.SerializeToString,
                response_deserializer=demo__pb2.ChatMessage.FromString,
                _registered_method=True)


class DemoServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """1. Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNumbers(self, request, context):
        """2. Server streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SumNumbers(self, request_iterator, context):
        """3. Client streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request_iterator, context):
        """4. Bidirecional streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DemoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=demo__pb2.HelloRequest.FromString,
                    response_serializer=demo__pb2.HelloReply.SerializeToString,
            ),
            'ListNumbers': grpc.unary_stream_rpc_method_handler(
                    servicer.ListNumbers,
                    request_deserializer=demo__pb2.RangeRequest.FromString,
                    response_serializer=demo__pb2.NumberReply.SerializeToString,
            ),
            'SumNumbers': grpc.stream_unary_rpc_method_handler(
                    servicer.SumNumbers,
                    request_deserializer=demo__pb2.NumberRequest.FromString,
                    response_serializer=demo__pb2.SumReply.SerializeToString,
            ),
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=demo__pb2.ChatMessage.FromString,
                    response_serializer=demo__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.DemoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('demo.DemoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DemoService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.DemoService/SayHello',
            demo__pb2.HelloRequest.SerializeToString,
            demo__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNumbers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/demo.DemoService/ListNumbers',
            demo__pb2.RangeRequest.SerializeToString,
            demo__pb2.NumberReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SumNumbers(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/demo.DemoService/SumNumbers',
            demo__pb2.NumberRequest.SerializeToString,
            demo__pb2.SumReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/demo.DemoService/Chat',
            demo__pb2.ChatMessage.SerializeToString,
            demo__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
