# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calc.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'calc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncalc.proto\x12\x04\x63\x61lc\"%\n\rBinaryRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\x19\n\x0cUnaryRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\"*\n\tCalcReply\x12\x0e\n\x06result\x18\x01 \x01(\x01\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xcf\x01\n\x0c\x42\x61sicService\x12+\n\x03\x41\x64\x64\x12\x13.calc.BinaryRequest\x1a\x0f.calc.CalcReply\x12\x30\n\x08Subtract\x12\x13.calc.BinaryRequest\x1a\x0f.calc.CalcReply\x12\x30\n\x08Multiply\x12\x13.calc.BinaryRequest\x1a\x0f.calc.CalcReply\x12.\n\x06\x44ivide\x12\x13.calc.BinaryRequest\x1a\x0f.calc.CalcReply2\xd2\x01\n\x0f\x41\x64vancedService\x12-\n\x05Power\x12\x13.calc.BinaryRequest\x1a\x0f.calc.CalcReply\x12\x31\n\nSquareRoot\x12\x12.calc.UnaryRequest\x1a\x0f.calc.CalcReply\x12\x30\n\tFactorial\x12\x12.calc.UnaryRequest\x1a\x0f.calc.CalcReply\x12+\n\x03Log\x12\x13.calc.BinaryRequest\x1a\x0f.calc.CalcReplyB\rZ\x0b./calc_grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013./calc_grpc'
  _globals['_BINARYREQUEST']._serialized_start=20
  _globals['_BINARYREQUEST']._serialized_end=57
  _globals['_UNARYREQUEST']._serialized_start=59
  _globals['_UNARYREQUEST']._serialized_end=84
  _globals['_CALCREPLY']._serialized_start=86
  _globals['_CALCREPLY']._serialized_end=128
  _globals['_BASICSERVICE']._serialized_start=131
  _globals['_BASICSERVICE']._serialized_end=338
  _globals['_ADVANCEDSERVICE']._serialized_start=341
  _globals['_ADVANCEDSERVICE']._serialized_end=551
# @@protoc_insertion_point(module_scope)
