# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calc_pb2 as calc__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in calc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BasicServiceStub:
    """Service A — basic operations (Python, port 50051)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/calc.BasicService/Add',
                request_serializer=calc__pb2.BinaryRequest.SerializeToString,
                response_deserializer=calc__pb2.CalcReply.FromString,
                _registered_method=True)
        self.Subtract = channel.unary_unary(
                '/calc.BasicService/Subtract',
                request_serializer=calc__pb2.BinaryRequest.SerializeToString,
                response_deserializer=calc__pb2.CalcReply.FromString,
                _registered_method=True)
        self.Multiply = channel.unary_unary(
                '/calc.BasicService/Multiply',
                request_serializer=calc__pb2.BinaryRequest.SerializeToString,
                response_deserializer=calc__pb2.CalcReply.FromString,
                _registered_method=True)
        self.Divide = channel.unary_unary(
                '/calc.BasicService/Divide',
                request_serializer=calc__pb2.BinaryRequest.SerializeToString,
                response_deserializer=calc__pb2.CalcReply.FromString,
                _registered_method=True)


class BasicServiceServicer:
    """Service A — basic operations (Python, port 50051)
    """

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subtract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Divide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BasicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=calc__pb2.BinaryRequest.FromString,
                    response_serializer=calc__pb2.CalcReply.SerializeToString,
            ),
            'Subtract': grpc.unary_unary_rpc_method_handler(
                    servicer.Subtract,
                    request_deserializer=calc__pb2.BinaryRequest.FromString,
                    response_serializer=calc__pb2.CalcReply.SerializeToString,
            ),
            'Multiply': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiply,
                    request_deserializer=calc__pb2.BinaryRequest.FromString,
                    response_serializer=calc__pb2.CalcReply.SerializeToString,
            ),
            'Divide': grpc.unary_unary_rpc_method_handler(
                    servicer.Divide,
                    request_deserializer=calc__pb2.BinaryRequest.FromString,
                    response_serializer=calc__pb2.CalcReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calc.BasicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calc.BasicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BasicService:
    """Service A — basic operations (Python, port 50051)
    """

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calc.BasicService/Add',
            calc__pb2.BinaryRequest.SerializeToString,
            calc__pb2.CalcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subtract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calc.BasicService/Subtract',
            calc__pb2.BinaryRequest.SerializeToString,
            calc__pb2.CalcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Multiply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calc.BasicService/Multiply',
            calc__pb2.BinaryRequest.SerializeToString,
            calc__pb2.CalcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Divide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calc.BasicService/Divide',
            calc__pb2.BinaryRequest.SerializeToString,
            calc__pb2.CalcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AdvancedServiceStub:
    """Service B — advanced operations (Node.js, port 50052)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Power = channel.unary_unary(
                '/calc.AdvancedService/Power',
                request_serializer=calc__pb2.BinaryRequest.SerializeToString,
                response_deserializer=calc__pb2.CalcReply.FromString,
                _registered_method=True)
        self.SquareRoot = channel.unary_unary(
                '/calc.AdvancedService/SquareRoot',
                request_serializer=calc__pb2.UnaryRequest.SerializeToString,
                response_deserializer=calc__pb2.CalcReply.FromString,
                _registered_method=True)
        self.Factorial = channel.unary_unary(
                '/calc.AdvancedService/Factorial',
                request_serializer=calc__pb2.UnaryRequest.SerializeToString,
                response_deserializer=calc__pb2.CalcReply.FromString,
                _registered_method=True)
        self.Log = channel.unary_unary(
                '/calc.AdvancedService/Log',
                request_serializer=calc__pb2.BinaryRequest.SerializeToString,
                response_deserializer=calc__pb2.CalcReply.FromString,
                _registered_method=True)


class AdvancedServiceServicer:
    """Service B — advanced operations (Node.js, port 50052)
    """

    def Power(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SquareRoot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Factorial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Log(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdvancedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Power': grpc.unary_unary_rpc_method_handler(
                    servicer.Power,
                    request_deserializer=calc__pb2.BinaryRequest.FromString,
                    response_serializer=calc__pb2.CalcReply.SerializeToString,
            ),
            'SquareRoot': grpc.unary_unary_rpc_method_handler(
                    servicer.SquareRoot,
                    request_deserializer=calc__pb2.UnaryRequest.FromString,
                    response_serializer=calc__pb2.CalcReply.SerializeToString,
            ),
            'Factorial': grpc.unary_unary_rpc_method_handler(
                    servicer.Factorial,
                    request_deserializer=calc__pb2.UnaryRequest.FromString,
                    response_serializer=calc__pb2.CalcReply.SerializeToString,
            ),
            'Log': grpc.unary_unary_rpc_method_handler(
                    servicer.Log,
                    request_deserializer=calc__pb2.BinaryRequest.FromString,
                    response_serializer=calc__pb2.CalcReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calc.AdvancedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calc.AdvancedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdvancedService:
    """Service B — advanced operations (Node.js, port 50052)
    """

    @staticmethod
    def Power(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calc.AdvancedService/Power',
            calc__pb2.BinaryRequest.SerializeToString,
            calc__pb2.CalcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SquareRoot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calc.AdvancedService/SquareRoot',
            calc__pb2.UnaryRequest.SerializeToString,
            calc__pb2.CalcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Factorial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calc.AdvancedService/Factorial',
            calc__pb2.UnaryRequest.SerializeToString,
            calc__pb2.CalcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Log(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calc.AdvancedService/Log',
            calc__pb2.BinaryRequest.SerializeToString,
            calc__pb2.CalcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
